/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type Video = {
  _id: string;
  _type: "video";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  videoId?: string;
  provider?: "youtube" | "vimeo" | "bunny";
  url?: string;
  title?: string;
  duration?: number;
  chaptersSource?: "youtube" | "synthesized" | "none";
  chapters?: Array<{
    startSeconds?: number;
    label?: string;
    _type: "videoChapter";
    _key: string;
  }>;
  chunks?: Array<{
    startSeconds?: number;
    text?: string;
    _type: "videoChunk";
    _key: string;
  }>;
  ingestedAt?: string;
};

export type InstructorReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "instructor";
};

export type CategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "category";
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Course = {
  _id: string;
  _type: "course";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  instructor?: InstructorReference;
  category?: CategoryReference;
  summary?: string;
  coverImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  level?: "Beginner" | "Intermediate" | "Advanced";
  price?: number;
  popular?: boolean;
  studentCount?: number;
  learningOutcomes?: Array<
    {
      _key: string;
    } & LearningOutcome
  >;
  modules?: Array<
    {
      _key: string;
    } & Module
  >;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Lesson = {
  _id: string;
  _type: "lesson";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  freePreview?: boolean;
  studentCount?: number;
  videoUrl?: string;
  poster?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  duration?: number;
  keyPoints?: Array<string>;
  notes?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "normal" | "h2" | "h3" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        _type: "image";
        _key: string;
      }
  >;
  proTip?: string;
  resources?: Array<
    {
      _key: string;
    } & Resource
  >;
};

export type Instructor = {
  _id: string;
  _type: "instructor";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  photo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  expertise?: Array<string>;
  bio?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
};

export type LessonReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "lesson";
};

export type Module = {
  _type: "module";
  title?: string;
  summary?: string;
  lessons?: Array<
    {
      _key: string;
    } & LessonReference
  >;
};

export type Resource = {
  _type: "resource";
  type?: "link" | "pdf" | "code" | "download" | "video";
  title?: string;
  description?: string;
  url?: string;
};

export type LearningOutcome = {
  _type: "learningOutcome";
  icon?: string;
  title?: string;
  description?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | Video
  | InstructorReference
  | CategoryReference
  | SanityImageAssetReference
  | Course
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | Lesson
  | Instructor
  | Category
  | LessonReference
  | Module
  | Resource
  | LearningOutcome
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../sanity/queries/categories.ts
// Variable: CATEGORIES_QUERY
// Query: *[_type == "category" && defined(slug.current)] | order(title asc) {      _id,  title,  "slug": slug.current,  description  }
export type CATEGORIES_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  description: string | null;
}>;

// Source: ../sanity/queries/categories.ts
// Variable: CATEGORY_BY_SLUG_QUERY
// Query: *[_type == "category" && slug.current == $slug][0] {      _id,  title,  "slug": slug.current,  description,    "courses": *[_type == "course" && references(^._id)]      | order(popular desc, _createdAt desc) {        _id,  title,  "slug": slug.current,  summary,  level,  price,  popular,  studentCount,  "coverImage": coverImage{   asset->{    _id,    url,    metadata { lqip, dimensions }  },  "alt": coalesce(alt, "") },  "instructor": instructor->{ _id, name, "slug": slug.current },  "category": category->{ _id, title, "slug": slug.current },  "moduleCount": count(modules),  "lessonCount": count(modules[].lessons[]),  "totalDurationSeconds": math::sum(modules[].lessons[]->duration)    }  }
export type CATEGORY_BY_SLUG_QUERY_RESULT = {
  _id: string;
  title: string | null;
  slug: string | null;
  description: string | null;
  courses: Array<{
    _id: string;
    title: string | null;
    slug: string | null;
    summary: string | null;
    level: "Advanced" | "Beginner" | "Intermediate" | null;
    price: number | null;
    popular: boolean | null;
    studentCount: number | null;
    coverImage: {
      asset: {
        _id: string;
        url: string | null;
        metadata: {
          lqip: string | null;
          dimensions: SanityImageDimensions | null;
        } | null;
      } | null;
      alt: string | "";
    } | null;
    instructor: {
      _id: string;
      name: string | null;
      slug: string | null;
    } | null;
    category: {
      _id: string;
      title: string | null;
      slug: string | null;
    } | null;
    moduleCount: number | null;
    lessonCount: number | null;
    totalDurationSeconds: number | null;
  }>;
} | null;

// Source: ../sanity/queries/courses.ts
// Variable: COURSES_QUERY
// Query: *[_type == "course" && defined(slug.current)]    | order(popular desc, _createdAt desc) {      _id,  title,  "slug": slug.current,  summary,  level,  price,  popular,  studentCount,  "coverImage": coverImage{   asset->{    _id,    url,    metadata { lqip, dimensions }  },  "alt": coalesce(alt, "") },  "instructor": instructor->{ _id, name, "slug": slug.current },  "category": category->{ _id, title, "slug": slug.current },  "moduleCount": count(modules),  "lessonCount": count(modules[].lessons[]),  "totalDurationSeconds": math::sum(modules[].lessons[]->duration)  }
export type COURSES_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  summary: string | null;
  level: "Advanced" | "Beginner" | "Intermediate" | null;
  price: number | null;
  popular: boolean | null;
  studentCount: number | null;
  coverImage: {
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        lqip: string | null;
        dimensions: SanityImageDimensions | null;
      } | null;
    } | null;
    alt: string | "";
  } | null;
  instructor: {
    _id: string;
    name: string | null;
    slug: string | null;
  } | null;
  category: {
    _id: string;
    title: string | null;
    slug: string | null;
  } | null;
  moduleCount: number | null;
  lessonCount: number | null;
  totalDurationSeconds: number | null;
}>;

// Source: ../sanity/queries/courses.ts
// Variable: FEATURED_COURSES_QUERY
// Query: *[_type == "course" && defined(slug.current) && popular == true]    | order(_createdAt desc)[0...6] {      _id,  title,  "slug": slug.current,  summary,  level,  price,  popular,  studentCount,  "coverImage": coverImage{   asset->{    _id,    url,    metadata { lqip, dimensions }  },  "alt": coalesce(alt, "") },  "instructor": instructor->{ _id, name, "slug": slug.current },  "category": category->{ _id, title, "slug": slug.current },  "moduleCount": count(modules),  "lessonCount": count(modules[].lessons[]),  "totalDurationSeconds": math::sum(modules[].lessons[]->duration)  }
export type FEATURED_COURSES_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  summary: string | null;
  level: "Advanced" | "Beginner" | "Intermediate" | null;
  price: number | null;
  popular: boolean | null;
  studentCount: number | null;
  coverImage: {
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        lqip: string | null;
        dimensions: SanityImageDimensions | null;
      } | null;
    } | null;
    alt: string | "";
  } | null;
  instructor: {
    _id: string;
    name: string | null;
    slug: string | null;
  } | null;
  category: {
    _id: string;
    title: string | null;
    slug: string | null;
  } | null;
  moduleCount: number | null;
  lessonCount: number | null;
  totalDurationSeconds: number | null;
}>;

// Source: ../sanity/queries/courses.ts
// Variable: COURSE_BY_SLUG_QUERY
// Query: *[_type == "course" && slug.current == $slug][0] {    _id,    title,    "slug": slug.current,    summary,    level,    price,    popular,    studentCount,    "coverImage": coverImage{   asset->{    _id,    url,    metadata { lqip, dimensions }  },  "alt": coalesce(alt, "") },    "instructor": instructor->{   _id,  name,  "slug": slug.current,  "photo": photo{   asset->{    _id,    url,    metadata { lqip, dimensions }  },  "alt": coalesce(alt, "") },  expertise },    "category": category->{      _id,      title,      "slug": slug.current,      description    },    learningOutcomes[]{      _key,      icon,      title,      description    },    "moduleCount": count(modules),    "lessonCount": count(modules[].lessons[]),    "totalDurationSeconds": math::sum(modules[].lessons[]->duration),    modules[]{      _key,      title,      summary,      "lessons": lessons[]->{   _id,  title,  "slug": slug.current,  duration,  freePreview,  studentCount,  "poster": poster{   asset->{    _id,    url,    metadata { lqip, dimensions }  },  "alt": coalesce(alt, "") },  keyPoints }    }  }
export type COURSE_BY_SLUG_QUERY_RESULT = {
  _id: string;
  title: string | null;
  slug: string | null;
  summary: string | null;
  level: "Advanced" | "Beginner" | "Intermediate" | null;
  price: number | null;
  popular: boolean | null;
  studentCount: number | null;
  coverImage: {
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        lqip: string | null;
        dimensions: SanityImageDimensions | null;
      } | null;
    } | null;
    alt: string | "";
  } | null;
  instructor: {
    _id: string;
    name: string | null;
    slug: string | null;
    photo: {
      asset: {
        _id: string;
        url: string | null;
        metadata: {
          lqip: string | null;
          dimensions: SanityImageDimensions | null;
        } | null;
      } | null;
      alt: string | "";
    } | null;
    expertise: Array<string> | null;
  } | null;
  category: {
    _id: string;
    title: string | null;
    slug: string | null;
    description: string | null;
  } | null;
  learningOutcomes: Array<{
    _key: string;
    icon: string | null;
    title: string | null;
    description: string | null;
  }> | null;
  moduleCount: number | null;
  lessonCount: number | null;
  totalDurationSeconds: number | null;
  modules: Array<{
    _key: string;
    title: string | null;
    summary: string | null;
    lessons: Array<{
      _id: string;
      title: string | null;
      slug: string | null;
      duration: number | null;
      freePreview: boolean | null;
      studentCount: number | null;
      poster: {
        asset: {
          _id: string;
          url: string | null;
          metadata: {
            lqip: string | null;
            dimensions: SanityImageDimensions | null;
          } | null;
        } | null;
        alt: string | "";
      } | null;
      keyPoints: Array<string> | null;
    }> | null;
  }> | null;
} | null;

// Source: ../sanity/queries/courses.ts
// Variable: COURSE_SLUGS_QUERY
// Query: *[_type == "course" && defined(slug.current)]{ "slug": slug.current }
export type COURSE_SLUGS_QUERY_RESULT = Array<{
  slug: string | null;
}>;

// Source: ../sanity/queries/instructors.ts
// Variable: INSTRUCTORS_QUERY
// Query: *[_type == "instructor" && defined(slug.current)] | order(name asc) {    _id,    name,    "slug": slug.current,    "photo": photo{   asset->{    _id,    url,    metadata { lqip, dimensions }  },  "alt": coalesce(alt, "") },    expertise  }
export type INSTRUCTORS_QUERY_RESULT = Array<{
  _id: string;
  name: string | null;
  slug: string | null;
  photo: {
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        lqip: string | null;
        dimensions: SanityImageDimensions | null;
      } | null;
    } | null;
    alt: string | "";
  } | null;
  expertise: Array<string> | null;
}>;

// Source: ../sanity/queries/instructors.ts
// Variable: INSTRUCTOR_BY_SLUG_QUERY
// Query: *[_type == "instructor" && slug.current == $slug][0] {      _id,  name,  "slug": slug.current,  "photo": photo{   asset->{    _id,    url,    metadata { lqip, dimensions }  },  "alt": coalesce(alt, "") },  expertise,    bio,    "courses": *[_type == "course" && references(^._id)]      | order(popular desc, _createdAt desc) {        _id,  title,  "slug": slug.current,  summary,  level,  price,  popular,  studentCount,  "coverImage": coverImage{   asset->{    _id,    url,    metadata { lqip, dimensions }  },  "alt": coalesce(alt, "") },  "instructor": instructor->{ _id, name, "slug": slug.current },  "category": category->{ _id, title, "slug": slug.current },  "moduleCount": count(modules),  "lessonCount": count(modules[].lessons[]),  "totalDurationSeconds": math::sum(modules[].lessons[]->duration)    }  }
export type INSTRUCTOR_BY_SLUG_QUERY_RESULT = {
  _id: string;
  name: string | null;
  slug: string | null;
  photo: {
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        lqip: string | null;
        dimensions: SanityImageDimensions | null;
      } | null;
    } | null;
    alt: string | "";
  } | null;
  expertise: Array<string> | null;
  bio: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  courses: Array<{
    _id: string;
    title: string | null;
    slug: string | null;
    summary: string | null;
    level: "Advanced" | "Beginner" | "Intermediate" | null;
    price: number | null;
    popular: boolean | null;
    studentCount: number | null;
    coverImage: {
      asset: {
        _id: string;
        url: string | null;
        metadata: {
          lqip: string | null;
          dimensions: SanityImageDimensions | null;
        } | null;
      } | null;
      alt: string | "";
    } | null;
    instructor: {
      _id: string;
      name: string | null;
      slug: string | null;
    } | null;
    category: {
      _id: string;
      title: string | null;
      slug: string | null;
    } | null;
    moduleCount: number | null;
    lessonCount: number | null;
    totalDurationSeconds: number | null;
  }>;
} | null;

// Source: ../sanity/queries/lessons.ts
// Variable: LESSON_BY_SLUG_QUERY
// Query: *[_type == "lesson" && slug.current == $slug][0] {    _id,    title,    "slug": slug.current,    videoUrl,    duration,    freePreview,    studentCount,    "poster": poster{   asset->{    _id,    url,    metadata { lqip, dimensions }  },  "alt": coalesce(alt, "") },    keyPoints,    proTip,    notes[]{      ...,      _type == "image" => {   asset->{    _id,    url,    metadata { lqip, dimensions }  },  "alt": coalesce(alt, "") }    },    resources[]{      _key,      type,      title,      description,      url    },    "course": *[_type == "course" && references(^._id)][0]{      _id,      title,      "slug": slug.current,      "instructor": instructor->{ _id, name, "slug": slug.current },      modules[]{        _key,        title,        "lessonIds": lessons[]._ref      }    }  }
export type LESSON_BY_SLUG_QUERY_RESULT = {
  _id: string;
  title: string | null;
  slug: string | null;
  videoUrl: string | null;
  duration: number | null;
  freePreview: boolean | null;
  studentCount: number | null;
  poster: {
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        lqip: string | null;
        dimensions: SanityImageDimensions | null;
      } | null;
    } | null;
    alt: string | "";
  } | null;
  keyPoints: Array<string> | null;
  proTip: string | null;
  notes: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "blockquote" | "h2" | "h3" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset: {
          _id: string;
          url: string | null;
          metadata: {
            lqip: string | null;
            dimensions: SanityImageDimensions | null;
          } | null;
        } | null;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt: string | "";
        _type: "image";
        _key: string;
      }
  > | null;
  resources: Array<{
    _key: string;
    type: "code" | "download" | "link" | "pdf" | "video" | null;
    title: string | null;
    description: string | null;
    url: string | null;
  }> | null;
  course: {
    _id: string;
    title: string | null;
    slug: string | null;
    instructor: {
      _id: string;
      name: string | null;
      slug: string | null;
    } | null;
    modules: Array<{
      _key: string;
      title: string | null;
      lessonIds: Array<string> | null;
    }> | null;
  } | null;
} | null;

// Source: ../sanity/queries/lessons.ts
// Variable: LESSON_SLUGS_QUERY
// Query: *[_type == "lesson" && defined(slug.current)]{ "slug": slug.current }
export type LESSON_SLUGS_QUERY_RESULT = Array<{
  slug: string | null;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "category" && defined(slug.current)] | order(title asc) {\n    \n  _id,\n  title,\n  "slug": slug.current,\n  description\n\n  }\n': CATEGORIES_QUERY_RESULT;
    '\n  *[_type == "category" && slug.current == $slug][0] {\n    \n  _id,\n  title,\n  "slug": slug.current,\n  description\n,\n    "courses": *[_type == "course" && references(^._id)]\n      | order(popular desc, _createdAt desc) {\n      \n  _id,\n  title,\n  "slug": slug.current,\n  summary,\n  level,\n  price,\n  popular,\n  studentCount,\n  "coverImage": coverImage{ \n  asset->{\n    _id,\n    url,\n    metadata { lqip, dimensions }\n  },\n  "alt": coalesce(alt, "")\n },\n  "instructor": instructor->{ _id, name, "slug": slug.current },\n  "category": category->{ _id, title, "slug": slug.current },\n  "moduleCount": count(modules),\n  "lessonCount": count(modules[].lessons[]),\n  "totalDurationSeconds": math::sum(modules[].lessons[]->duration)\n\n    }\n  }\n': CATEGORY_BY_SLUG_QUERY_RESULT;
    '\n  *[_type == "course" && defined(slug.current)]\n    | order(popular desc, _createdAt desc) {\n    \n  _id,\n  title,\n  "slug": slug.current,\n  summary,\n  level,\n  price,\n  popular,\n  studentCount,\n  "coverImage": coverImage{ \n  asset->{\n    _id,\n    url,\n    metadata { lqip, dimensions }\n  },\n  "alt": coalesce(alt, "")\n },\n  "instructor": instructor->{ _id, name, "slug": slug.current },\n  "category": category->{ _id, title, "slug": slug.current },\n  "moduleCount": count(modules),\n  "lessonCount": count(modules[].lessons[]),\n  "totalDurationSeconds": math::sum(modules[].lessons[]->duration)\n\n  }\n': COURSES_QUERY_RESULT;
    '\n  *[_type == "course" && defined(slug.current) && popular == true]\n    | order(_createdAt desc)[0...6] {\n    \n  _id,\n  title,\n  "slug": slug.current,\n  summary,\n  level,\n  price,\n  popular,\n  studentCount,\n  "coverImage": coverImage{ \n  asset->{\n    _id,\n    url,\n    metadata { lqip, dimensions }\n  },\n  "alt": coalesce(alt, "")\n },\n  "instructor": instructor->{ _id, name, "slug": slug.current },\n  "category": category->{ _id, title, "slug": slug.current },\n  "moduleCount": count(modules),\n  "lessonCount": count(modules[].lessons[]),\n  "totalDurationSeconds": math::sum(modules[].lessons[]->duration)\n\n  }\n': FEATURED_COURSES_QUERY_RESULT;
    '\n  *[_type == "course" && slug.current == $slug][0] {\n    _id,\n    title,\n    "slug": slug.current,\n    summary,\n    level,\n    price,\n    popular,\n    studentCount,\n    "coverImage": coverImage{ \n  asset->{\n    _id,\n    url,\n    metadata { lqip, dimensions }\n  },\n  "alt": coalesce(alt, "")\n },\n    "instructor": instructor->{ \n  _id,\n  name,\n  "slug": slug.current,\n  "photo": photo{ \n  asset->{\n    _id,\n    url,\n    metadata { lqip, dimensions }\n  },\n  "alt": coalesce(alt, "")\n },\n  expertise\n },\n    "category": category->{\n      _id,\n      title,\n      "slug": slug.current,\n      description\n    },\n    learningOutcomes[]{\n      _key,\n      icon,\n      title,\n      description\n    },\n    "moduleCount": count(modules),\n    "lessonCount": count(modules[].lessons[]),\n    "totalDurationSeconds": math::sum(modules[].lessons[]->duration),\n    modules[]{\n      _key,\n      title,\n      summary,\n      "lessons": lessons[]->{ \n  _id,\n  title,\n  "slug": slug.current,\n  duration,\n  freePreview,\n  studentCount,\n  "poster": poster{ \n  asset->{\n    _id,\n    url,\n    metadata { lqip, dimensions }\n  },\n  "alt": coalesce(alt, "")\n },\n  keyPoints\n }\n    }\n  }\n': COURSE_BY_SLUG_QUERY_RESULT;
    '\n  *[_type == "course" && defined(slug.current)]{ "slug": slug.current }\n': COURSE_SLUGS_QUERY_RESULT;
    '\n  *[_type == "instructor" && defined(slug.current)] | order(name asc) {\n    _id,\n    name,\n    "slug": slug.current,\n    "photo": photo{ \n  asset->{\n    _id,\n    url,\n    metadata { lqip, dimensions }\n  },\n  "alt": coalesce(alt, "")\n },\n    expertise\n  }\n': INSTRUCTORS_QUERY_RESULT;
    '\n  *[_type == "instructor" && slug.current == $slug][0] {\n    \n  _id,\n  name,\n  "slug": slug.current,\n  "photo": photo{ \n  asset->{\n    _id,\n    url,\n    metadata { lqip, dimensions }\n  },\n  "alt": coalesce(alt, "")\n },\n  expertise\n,\n    bio,\n    "courses": *[_type == "course" && references(^._id)]\n      | order(popular desc, _createdAt desc) {\n      \n  _id,\n  title,\n  "slug": slug.current,\n  summary,\n  level,\n  price,\n  popular,\n  studentCount,\n  "coverImage": coverImage{ \n  asset->{\n    _id,\n    url,\n    metadata { lqip, dimensions }\n  },\n  "alt": coalesce(alt, "")\n },\n  "instructor": instructor->{ _id, name, "slug": slug.current },\n  "category": category->{ _id, title, "slug": slug.current },\n  "moduleCount": count(modules),\n  "lessonCount": count(modules[].lessons[]),\n  "totalDurationSeconds": math::sum(modules[].lessons[]->duration)\n\n    }\n  }\n': INSTRUCTOR_BY_SLUG_QUERY_RESULT;
    '\n  *[_type == "lesson" && slug.current == $slug][0] {\n    _id,\n    title,\n    "slug": slug.current,\n    videoUrl,\n    duration,\n    freePreview,\n    studentCount,\n    "poster": poster{ \n  asset->{\n    _id,\n    url,\n    metadata { lqip, dimensions }\n  },\n  "alt": coalesce(alt, "")\n },\n    keyPoints,\n    proTip,\n    notes[]{\n      ...,\n      _type == "image" => { \n  asset->{\n    _id,\n    url,\n    metadata { lqip, dimensions }\n  },\n  "alt": coalesce(alt, "")\n }\n    },\n    resources[]{\n      _key,\n      type,\n      title,\n      description,\n      url\n    },\n    "course": *[_type == "course" && references(^._id)][0]{\n      _id,\n      title,\n      "slug": slug.current,\n      "instructor": instructor->{ _id, name, "slug": slug.current },\n      modules[]{\n        _key,\n        title,\n        "lessonIds": lessons[]._ref\n      }\n    }\n  }\n': LESSON_BY_SLUG_QUERY_RESULT;
    '\n  *[_type == "lesson" && defined(slug.current)]{ "slug": slug.current }\n': LESSON_SLUGS_QUERY_RESULT;
  }
}
